# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
################################################################################
Organizations:
    - &OrgGov
        Name: OrgGovMSP
        ID: OrgGovMSP

        MSPDir: ../organizations/peerOrganizations/orggov.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgGovMSP.admin', 'OrgGovMSP.peer', 'OrgGovMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgGovMSP.admin', 'OrgGovMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgGovMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgGovMSP.peer')"
